# Generated by Django 4.0.6 on 2022-07-27 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Genre name.', max_length=150, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'genre',
                'verbose_name_plural': 'genres',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Title of the video.', max_length=250, verbose_name='title')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('video_file', models.FileField(help_text='Path to the uploaded video.', upload_to='videos', verbose_name='Video file')),
                ('thumbnail', models.ImageField(help_text='An image that will be used as a thumbnail.', upload_to='thumbnails', verbose_name='thumbnail')),
                ('description', models.TextField(help_text='Description of the video.', max_length=1000, verbose_name='description')),
                ('privacy', models.CharField(choices=[('PR', 'Private'), ('PU', 'Public')], default='PU', max_length=2, verbose_name='privacy')),
                ('movie_rating', models.CharField(choices=[('G', 'General Audience'), ('PG', 'Parental Guidance Suggested'), ('M', 'Mature Audience Only')], max_length=2, verbose_name='movie rating')),
                ('impressions', models.PositiveBigIntegerField(default=0, help_text='View count for a video.', verbose_name='impressions')),
                ('released', models.DateField(blank=True, null=True)),
                ('enable_comments', models.BooleanField(default=True, help_text='Flag to turn on/off commenting', verbose_name='enable comments')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date/time when the user uploaded the video', verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The date/time when the user made changes to the video information', verbose_name='updated')),
                ('favorites', models.ManyToManyField(blank=True, help_text='Users who added video to their favorites.', null=True, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='user favorites')),
                ('genre', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='videos', to='videos.genre', verbose_name='genre')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
                'ordering': ['-created'],
            },
        ),
    ]
